### ISSUE TITLE
How to keep setup mode-line to use `fixed-pitch-mode`?

### ISSUE THREAD

**Issue by Yevgnen** [cstby/fixed-pitch-mode#1]
Do I have to setup each face individually outside `fixed-pitch-mode`? Thanks.

**Comment by cstby** [comment]
Unfortunately, yes. This package uses `buffer-set-face` to change the face for an entire buffer. The mode line is sort of special and isn't treated like a buffer.

As you mentioned, one option would be to set the mode line faces to inherit from your fixed-pitch face.
Another option would be to use a more minimal modeline package. I use [doom modeline](https://github.com/seagle0128/doom-modeline), which right-aligns everything after the buffer percent indicator. (The percentage indicator itself shifts around a little, but not enough that I'm bothered by it.)

In any case, the problem can't be solved here.
