### ISSUE TITLE
Eshell

### ISSUE THREAD

**Issue by gety9** [cstby/fixed-pitch-mode#2]
Hello, 

thanks for great package!

Could you tell how to apply fixed pitch to Eshell? (M-x Eshell)

I tried
```
(use-package fixed-pitch
  :load-path ...
  :custom
  (fixed-pitch-whitelist-hooks
    '(eshell-mode-hook
    eshell-load-hook)
  )
)
```

But no luck.

**Comment by ParetoOptimalDev** [comment]
I had to add `:demand t` for it to work.

**Comment by gety9** [comment]
@ParetoOptimalDev 

Thank you, it solved it!

(also required emacs restart, eval-buffer on init.el didn't cut it)
